name: snt_ui_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  country_picker: ^2.0.27
  flutter_animate: ^4.5.2
  lottie: ^3.3.1
  google_fonts: ^6.3.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  retrofit: ^4.7.2
  json_annotation: ^4.9.0
  json_serializable: ^6.10.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.1.5
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  intl: 0.20.2
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2
  vibration: ^3.1.3
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  confetti: ^0.8.0
  audioplayers: ^6.5.0
  internet_connection_checker: ^3.0.1

  flutter_multi_formatter: ^2.13.9
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.10.0
  remixicon: ^1.4.1
  eva_icons_flutter: ^3.1.0
  heroicons: ^0.11.0
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  retrofit_generator: ^10.0.2
  hive_ce_generator: ^1.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/onboarding1.json
    - assets/lotties/onboarding2.json
    - assets/lotties/onboarding3.json
    - assets/images/
    - assets/images/auth/
    - assets/images/payment/
    - assets/lotties/
    - assets/images/payment/wave.png
