// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:snt_ui_test/app/data/models/contribution.dart';
import 'package:snt_ui_test/app/data/models/tontine.dart';
import 'package:snt_ui_test/app/data/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AchievementAdapter());
    registerAdapter(AppUserAdapter());
    registerAdapter(ContributionAdapter());
    registerAdapter(ContributionStatusAdapter());
    registerAdapter(TontineAdapter());
    registerAdapter(TontineCategoryAdapter());
    registerAdapter(TontineDrawOrderAdapter());
    registerAdapter(TontineFrequencyAdapter());
    registerAdapter(TontineStatusAdapter());
    registerAdapter(UserLevelAdapter());
    registerAdapter(UserPreferencesAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AchievementAdapter());
    registerAdapter(AppUserAdapter());
    registerAdapter(ContributionAdapter());
    registerAdapter(ContributionStatusAdapter());
    registerAdapter(TontineAdapter());
    registerAdapter(TontineCategoryAdapter());
    registerAdapter(TontineDrawOrderAdapter());
    registerAdapter(TontineFrequencyAdapter());
    registerAdapter(TontineStatusAdapter());
    registerAdapter(UserLevelAdapter());
    registerAdapter(UserPreferencesAdapter());
  }
}
